---
name: Supported
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # runs at 2:30 UTC every Sunday
    - cron: '30 2 * * 0'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0

      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install python dependencies
        run: |
          echo ::group::PYDEPS
          pip install gitpython requests packaging jinja2 pyyaml
          echo ::endgroup::

      - name: Configure Git with pulpbot name and email
        run: |
          git config --global user.name 'pulpbot'
          git config --global user.email 'pulp-infra@redhat.com'

      - name: Get supported
        run: python .github/supported_version.py
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Run update
        run: |
          .github/workflows/scripts/update_ci.sh

      - name: Update supported versions
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          committer: pulpbot <pulp-infra@redhat.com>
          author: pulpbot <pulp-infra@redhat.com>
          title: Update supported versions
          body: '[noissue]'
          branch: 'create-pull-request/versions/patch'
          commit-message: |
            Update supported versions

            [noissue]
          delete-branch: true
